name: gemini_voice_app
description: Gemini Voice Chat App
version: 1.1.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
