name: gemini_voice_app
description: Gemini Voice Chat App
version: 1.1.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  speech_to_text: ^6.6.0
  permission_handler: ^11.0.1
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.2
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  uuid: ^4.0.0
  dio: ^5.4.0
  path_provider: ^2.1.1
  android_intent_plus: ^4.0.3

flutter:
  uses-material-design: true
