name: gemini_voice_app
description: Gemini Voice Chat App
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.2

flutter:
  uses-material-design: true
